name: Release 📦

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: kolvin/github-actions/.github/workflows/automated-semver.yaml@31be6c5d5ee5da0bd16b61dac25f11194170e328
    secrets:
      BOT_GPG_PRIVATE_KEY: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
      BOT_GPG_PASSPHRASE: ${{ secrets.BOT_GPG_PASSPHRASE }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

